@host = http://localhost
@path = /wpsdp/wp-json/seminardesk/v1/webhooks HTTP/1.1
@url = {{host}}{{path}}
@auth = Basic c2VtaW5hcmRlc2s6XlQ0cWVNNHYkTjhuRWRVVWRGbTJUdjRj
@content = application/json
@timestamp = "{{$timestamp}}"
@guid = "{{$guid}}"

### 721 - 927cd29a247a4cfdba3fad6b3335a430 - Market Garden System - Nachhaltig & Regenerativ
POST {{url}}
Authorization: {{auth}}
Content-Type: {{content}}

{
    "action": "eventDate.create",
    "timestamp": 1583509808000,
    "requestId": "3b27fe327ae240bf838a3fb6693e9feb",
    "payload": {
        "id": 721,
        "eventId": "927cd29a247a4cfdba3fad6b3335a430",
        "status": "available",
        "registrationAvailable": true,
        "detailpageAvailable": true,
        "beginDate": "1599755400000",
        "endDate": "1599998400000",
        "title": [
            {
                "language": "DE",
                "value": "Market Garden System - Nachhaltig & Regenerativ"
            }
        ],
        "titleSlug": [
            {
                "language": "DE",
                "value": "market-garden-system---nachhaltig--regenerativ"
            }
        ],
        "subtitle": [
            {
                "language": "DE",
                "value": "3-Tages-Kurs mit einzeln buchbaren Modulen, Veranstalter: Sebastian Heilmann, Maya Lukoff und Urs Mauk"
            }
        ],
        "teaser": [
            {
                "language": "DE",
                "value": "Kann Market Gardening (MG) als intensives System dennoch nachhaltig und regenerativ sein? <br /><br />Wir  sind der Meinung: grundsätzlich ja! Jedoch braucht es dazu ein  Verständnis über die Zusammenhänge im Boden und geeignete Methoden bzw.  Werkzeuge, um die Bodenfruchtbarkeit zu erhalten und zu verbessern. Am  Freitag werden wir diese Grundlagen legen, auf die dann in den folgenden  Tagen die eher technischen Details des MG aufbauen.<br />"
            }
        ],
        "teaserPictureUrl": [
            {
                "language": "DE",
                "value": "https://schloss-tempelhof.seminardesk.de/Content/Extern/MarketGarden32.jpg"
            }
        ],
        "priceInfo": [
            {
                "language": "DE",
                "value": "Ab 18 Jahren 320 Euro\r\n"
            }
        ],
        "facilitators": [
            123,
            124,
            125
        ],
        "venue": null,
        "contactInfo": null,
        "eventType": "",
        "eventTopic": "Ökologie",
        "showAttendanceFees": true
    }
}

### 722 - 927cd29a247a4cfdba3fad6b3335a430 - Market Garden System - Nachhaltig & Regenerativ
POST {{url}}
Authorization: {{auth}}
Content-Type: {{content}}

{
    "action": "eventDate.create",
    "timestamp": 1583509808000,
    "requestId": "3b27fe327ae240bf838a3fb6693e9feb",
    "payload": {
        "id": 722,
        "eventId": "927cd29a247a4cfdba3fad6b3335a430",
        "status": "available",
        "registrationAvailable": true,
        "detailpageAvailable": true,
        "beginDate": "1599755400000",
        "endDate": "1599832800000",
        "title": [
            {
                "language": "DE",
                "value": "Market Garden System - Nachhaltig & Regenerativ"
            }
        ],
        "titleSlug": [
            {
                "language": "DE",
                "value": "market-garden-system---nachhaltig--regenerativ"
            }
        ],
        "subtitle": [
            {
                "language": "DE",
                "value": "3-Tages-Kurs mit einzeln buchbaren Modulen, Veranstalter: Sebastian Heilmann, Maya Lukoff und Urs Mauk"
            }
        ],
        "teaser": [
            {
                "language": "DE",
                "value": "Kann Market Gardening (MG) als intensives System dennoch nachhaltig und regenerativ sein? <br /><br />Wir  sind der Meinung: grundsätzlich ja! Jedoch braucht es dazu ein  Verständnis über die Zusammenhänge im Boden und geeignete Methoden bzw.  Werkzeuge, um die Bodenfruchtbarkeit zu erhalten und zu verbessern. Am  Freitag werden wir diese Grundlagen legen, auf die dann in den folgenden  Tagen die eher technischen Details des MG aufbauen.<br />"
            }
        ],
        "teaserPictureUrl": [
            {
                "language": "DE",
                "value": "https://schloss-tempelhof.seminardesk.de/Content/Extern/MarketGarden32.jpg"
            }
        ],
        "priceInfo": [
            {
                "language": "DE",
                "value": "Ab 18 Jahren 130 Euro\r\n"
            }
        ],
        "facilitators": [
            123,
            124,
            125
        ],
        "venue": null,
        "contactInfo": null,
        "eventType": "",
        "eventTopic": "Ökologie",
        "showAttendanceFees": true
    }
}

### 723 - 927cd29a247a4cfdba3fad6b3335a430 - Market Garden System - Nachhaltig & Regenerativ

POST {{url}}
Authorization: {{auth}}
Content-Type: {{content}}

{
    "action": "eventDate.create",
    "timestamp": 1583509808000,
    "requestId": "3b27fe327ae240bf838a3fb6693e9feb",
    "payload": {
        "id": 723,
        "eventId": "927cd29a247a4cfdba3fad6b3335a430",
        "status": "available",
        "registrationAvailable": true,
        "detailpageAvailable": true,
        "beginDate": "1599836400000",
        "endDate": "1599998400000",
        "title": [
            {
                "language": "DE",
                "value": "Market Garden System - Nachhaltig & Regenerativ"
            }
        ],
        "titleSlug": [
            {
                "language": "DE",
                "value": "market-garden-system---nachhaltig--regenerativ"
            }
        ],
        "subtitle": [
            {
                "language": "DE",
                "value": "3-Tages-Kurs mit einzeln buchbaren Modulen, Veranstalter: Sebastian Heilmann, Maya Lukoff und Urs Mauk"
            }
        ],
        "teaser": [
            {
                "language": "DE",
                "value": "Kann Market Gardening (MG) als intensives System dennoch nachhaltig und regenerativ sein? <br /><br />Wir  sind der Meinung: grundsätzlich ja! Jedoch braucht es dazu ein  Verständnis über die Zusammenhänge im Boden und geeignete Methoden bzw.  Werkzeuge, um die Bodenfruchtbarkeit zu erhalten und zu verbessern. Am  Freitag werden wir diese Grundlagen legen, auf die dann in den folgenden  Tagen die eher technischen Details des MG aufbauen.<br />"
            }
        ],
        "teaserPictureUrl": [
            {
                "language": "DE",
                "value": "https://schloss-tempelhof.seminardesk.de/Content/Extern/MarketGarden32.jpg"
            }
        ],
        "priceInfo": [
            {
                "language": "DE",
                "value": "Ab 18 Jahren 240 Euro\r\n"
            }
        ],
        "facilitators": [
            123,
            124,
            125
        ],
        "venue": null,
        "contactInfo": null,
        "eventType": "",
        "eventTopic": "Ökologie",
        "showAttendanceFees": true
    }
}

### 726 - 927cd29a247a4cfdba3fad6b3335a430 - Market Garden System - Nachhaltig & Regenerativ

POST {{url}}
Authorization: {{auth}}
Content-Type: {{content}}

{
    "action": "eventDate.create",
    "timestamp": 1583509808000,
    "requestId": "3b27fe327ae240bf838a3fb6693e9feb",
    "payload": {
        "id": 726,
        "eventId": "927cd29a247a4cfdba3fad6b3335a430",
        "status": "available",
        "registrationAvailable": true,
        "detailpageAvailable": true,
        "beginDate": "1603384200000",
        "endDate": "1603630800000",
        "title": [
            {
                "language": "DE",
                "value": "Market Garden System - Nachhaltig & Regenerativ"
            }
        ],
        "titleSlug": [
            {
                "language": "DE",
                "value": "market-garden-system---nachhaltig--regenerativ"
            }
        ],
        "subtitle": [
            {
                "language": "DE",
                "value": "3-Tages-Kurs mit einzeln buchbaren Modulen, Veranstalter: Sebastian Heilmann, Maya Lukoff und Urs Mauk"
            }
        ],
        "teaser": [
            {
                "language": "DE",
                "value": "Kann Market Gardening (MG) als intensives System dennoch nachhaltig und regenerativ sein? <br /><br />Wir  sind der Meinung: grundsätzlich ja! Jedoch braucht es dazu ein  Verständnis über die Zusammenhänge im Boden und geeignete Methoden bzw.  Werkzeuge, um die Bodenfruchtbarkeit zu erhalten und zu verbessern. Am  Freitag werden wir diese Grundlagen legen, auf die dann in den folgenden  Tagen die eher technischen Details des MG aufbauen.<br />"
            }
        ],
        "teaserPictureUrl": [
            {
                "language": "DE",
                "value": "https://schloss-tempelhof.seminardesk.de/Content/Extern/MarketGarden32.jpg"
            }
        ],
        "priceInfo": [
            {
                "language": "DE",
                "value": "Ab 18 Jahren 320 Euro\r\n"
            }
        ],
        "facilitators": [
            123,
            124,
            125
        ],
        "venue": null,
        "contactInfo": null,
        "eventType": "",
        "eventTopic": "Ökologie",
        "showAttendanceFees": true
    }
}

### 727 - 927cd29a247a4cfdba3fad6b3335a430 - Market Garden System - Nachhaltig & Regenerativ

POST {{url}}
Authorization: {{auth}}
Content-Type: {{content}}

{
    "action": "eventDate.create",
    "timestamp": 1583509808000,
    "requestId": "3b27fe327ae240bf838a3fb6693e9feb",
    "payload": {
        "id": 727,
        "eventId": "927cd29a247a4cfdba3fad6b3335a430",
        "status": "available",
        "registrationAvailable": true,
        "detailpageAvailable": true,
        "beginDate": "1603384200000",
        "endDate": "1603461600000",
        "title": [
            {
                "language": "DE",
                "value": "Market Garden System - Nachhaltig & Regenerativ"
            }
        ],
        "titleSlug": [
            {
                "language": "DE",
                "value": "market-garden-system---nachhaltig--regenerativ"
            }
        ],
        "subtitle": [
            {
                "language": "DE",
                "value": "3-Tages-Kurs mit einzeln buchbaren Modulen, Veranstalter: Sebastian Heilmann, Maya Lukoff und Urs Mauk"
            }
        ],
        "teaser": [
            {
                "language": "DE",
                "value": "Kann Market Gardening (MG) als intensives System dennoch nachhaltig und regenerativ sein? <br /><br />Wir  sind der Meinung: grundsätzlich ja! Jedoch braucht es dazu ein  Verständnis über die Zusammenhänge im Boden und geeignete Methoden bzw.  Werkzeuge, um die Bodenfruchtbarkeit zu erhalten und zu verbessern. Am  Freitag werden wir diese Grundlagen legen, auf die dann in den folgenden  Tagen die eher technischen Details des MG aufbauen.<br />"
            }
        ],
        "teaserPictureUrl": [
            {
                "language": "DE",
                "value": "https://schloss-tempelhof.seminardesk.de/Content/Extern/MarketGarden32.jpg"
            }
        ],
        "priceInfo": [
            {
                "language": "DE",
                "value": "Ab 18 Jahren 320 Euro\r\n"
            }
        ],
        "facilitators": [
            123,
            124,
            125
        ],
        "venue": null,
        "contactInfo": null,
        "eventType": "",
        "eventTopic": "Ökologie",
        "showAttendanceFees": true
    }
}

### 728 - 927cd29a247a4cfdba3fad6b3335a430 - Market Garden System - Nachhaltig & Regenerativ

POST {{url}}
Authorization: {{auth}}
Content-Type: {{content}}

{
    "action": "eventDate.create",
    "timestamp": 1583509808000,
    "requestId": "3b27fe327ae240bf838a3fb6693e9feb",
    "payload": {
        "id": 728,
        "eventId": "927cd29a247a4cfdba3fad6b3335a430",
        "status": "available",
        "registrationAvailable": true,
        "detailpageAvailable": true,
        "beginDate": "1603465200000",
        "endDate": "1603630800000",
        "title": [
            {
                "language": "DE",
                "value": "Market Garden System - Nachhaltig & Regenerativ"
            }
        ],
        "titleSlug": [
            {
                "language": "DE",
                "value": "market-garden-system---nachhaltig--regenerativ"
            }
        ],
        "subtitle": [
            {
                "language": "DE",
                "value": "3-Tages-Kurs mit einzeln buchbaren Modulen, Veranstalter: Sebastian Heilmann, Maya Lukoff und Urs Mauk"
            }
        ],
        "teaser": [
            {
                "language": "DE",
                "value": "Kann Market Gardening (MG) als intensives System dennoch nachhaltig und regenerativ sein? <br /><br />Wir  sind der Meinung: grundsätzlich ja! Jedoch braucht es dazu ein  Verständnis über die Zusammenhänge im Boden und geeignete Methoden bzw.  Werkzeuge, um die Bodenfruchtbarkeit zu erhalten und zu verbessern. Am  Freitag werden wir diese Grundlagen legen, auf die dann in den folgenden  Tagen die eher technischen Details des MG aufbauen.<br />"
            }
        ],
        "teaserPictureUrl": [
            {
                "language": "DE",
                "value": "https://schloss-tempelhof.seminardesk.de/Content/Extern/MarketGarden32.jpg"
            }
        ],
        "priceInfo": [
            {
                "language": "DE",
                "value": "Ab 18 Jahren 320 Euro\r\n"
            }
        ],
        "facilitators": [
            123,
            124,
            125
        ],
        "venue": null,
        "contactInfo": null,
        "eventType": "",
        "eventTopic": "Ökologie",
        "showAttendanceFees": true
    }
}

### 922 - 50c7db655df54e0d8c03c851eb9a5ca8 - Kennenlernwochenende für Gemeinschaftsinteressierte

POST {{url}}
Authorization: {{auth}}
Content-Type: {{content}}

{
    "action": "eventDate.create",
    "timestamp": 1583509808000,
    "requestId": "3b27fe327ae240bf838a3fb6693e9feb",
    "payload": {
        "id": 922,
        "eventId": "50c7db655df54e0d8c03c851eb9a5ca8",
        "status": "available",
        "registrationAvailable": true,
        "detailpageAvailable": true,
        "beginDate": "1594917000000",
        "endDate": "1595160000000",
        "title": [
            {
                "language": "DE",
                "value": "Kennenlernwochenende für Gemeinschaftsinteressierte"
            }
        ],
        "titleSlug": [
            {
                "language": "DE",
                "value": "kennenlernwochenende-fur-gemeinschaftsinteressierte"
            }
        ],
        "subtitle": [
            {
                "language": "DE",
                "value": "Veranstalter: Schloss Tempelhof eG mit verschiedenen Begleitern aus der Gemeinschaft"
            }
        ],
        "teaser": [
            {
                "language": "DE",
                "value": "<div id=\"Teaser\"><p helvetica=\"\" neue\",=\"\" helvetica,=\"\" arial,=\"\" sans-serif;=\"\" font-size:=\"\" 14px;=\"\" background-color:=\"\" #ffffff;=\"\" text-decoration-style:=\"\" initial;=\"\" text-decoration-color:=\"\" initial;\"=\"\" style=\"color: #333333;\">Über  Projektinfos, Workshops, Vorstellung unserer Werte und Visionen, sowie  über die praktische Mitarbeit in kleinen Arbeitsgruppen können die  TeilnehmerInnen unsere Gemeinschaft kennenlernen. Themen wie  Gemeinschaftsbildung, Transformation der Ökonomie, Kommunikationskultur,  Konsensentscheidungen werden vorgestellt und im Gruppenprozess erlebt</p></div><br />"
            }
        ],
        "teaserPictureUrl": [
            {
                "language": "DE",
                "value": "https://schloss-tempelhof.seminardesk.de/Content/Extern/DSC00235-300x200[1].jpg"
            }
        ],
        "priceInfo": [
            {
                "language": "DE",
                "value": "nach Selbsteinschätzung"
            }
        ],
        "facilitators": [
            111,
            112,
            113
        ],
        "venue": null,
        "contactInfo": null,
        "eventType": "Kennenlernwochenende",
        "eventTopic": "Schloss Tempelhof Kennenlernen",
        "showAttendanceFees": true
    }
}

### 595 - 50c7db655df54e0d8c03c851eb9a5ca8 - Kennenlernwochenende für Gemeinschaftsinteressierte

POST {{url}}
Authorization: {{auth}}
Content-Type: {{content}}

{
    "action": "eventDate.create",
    "timestamp": 1583509808000,
    "requestId": "3b27fe327ae240bf838a3fb6693e9feb",
    "payload": {
        "id": 595,
        "eventId": "50c7db655df54e0d8c03c851eb9a5ca8",
        "status": "available",
        "registrationAvailable": true,
        "detailpageAvailable": true,
        "beginDate": "1599755400000",
        "endDate": "1599998400000",
        "title": [
            {
                "language": "DE",
                "value": "Kennenlernwochenende für Gemeinschaftsinteressierte"
            }
        ],
        "titleSlug": [
            {
                "language": "DE",
                "value": "kennenlernwochenende-fur-gemeinschaftsinteressierte"
            }
        ],
        "subtitle": [
            {
                "language": "DE",
                "value": "Veranstalter: Schloss Tempelhof eG mit verschiedenen Begleitern aus der Gemeinschaft"
            }
        ],
        "teaser": [
            {
                "language": "DE",
                "value": "<div id=\"Teaser\"><p helvetica=\"\" neue\",=\"\" helvetica,=\"\" arial,=\"\" sans-serif;=\"\" font-size:=\"\" 14px;=\"\" background-color:=\"\" #ffffff;=\"\" text-decoration-style:=\"\" initial;=\"\" text-decoration-color:=\"\" initial;\"=\"\" style=\"color: #333333;\">Über  Projektinfos, Workshops, Vorstellung unserer Werte und Visionen, sowie  über die praktische Mitarbeit in kleinen Arbeitsgruppen können die  TeilnehmerInnen unsere Gemeinschaft kennenlernen. Themen wie  Gemeinschaftsbildung, Transformation der Ökonomie, Kommunikationskultur,  Konsensentscheidungen werden vorgestellt und im Gruppenprozess erlebt</p></div><br />"
            }
        ],
        "teaserPictureUrl": [
            {
                "language": "DE",
                "value": "https://schloss-tempelhof.seminardesk.de/Content/Extern/DSC00235-300x200[1].jpg"
            }
        ],
        "priceInfo": [
            {
                "language": "DE",
                "value": "nach Selbsteinschätzung"
            }
        ],
        "facilitators": [
            111,
            112,
            113
        ],
        "venue": null,
        "contactInfo": null,
        "eventType": "Kennenlernwochenende",
        "eventTopic": "Schloss Tempelhof Kennenlernen",
        "showAttendanceFees": true
    }
}

### 596 - 50c7db655df54e0d8c03c851eb9a5ca8 - Kennenlernwochenende für Gemeinschaftsinteressierte

POST {{url}}
Authorization: {{auth}}
Content-Type: {{content}}

{
    "action": "eventDate.create",
    "timestamp": 1583509808000,
    "requestId": "3b27fe327ae240bf838a3fb6693e9feb",
    "payload": {
        "id": 596,
        "eventId": "50c7db655df54e0d8c03c851eb9a5ca8",
        "status": "available",
        "registrationAvailable": true,
        "detailpageAvailable": true,
        "beginDate": "1605202200000",
        "endDate": "1605445200000",
        "title": [
            {
                "language": "DE",
                "value": "Kennenlernwochenende für Gemeinschaftsinteressierte"
            }
        ],
        "titleSlug": [
            {
                "language": "DE",
                "value": "kennenlernwochenende-fur-gemeinschaftsinteressierte"
            }
        ],
        "subtitle": [
            {
                "language": "DE",
                "value": "Veranstalter: Schloss Tempelhof eG mit verschiedenen Begleitern aus der Gemeinschaft"
            }
        ],
        "teaser": [
            {
                "language": "DE",
                "value": "<div id=\"Teaser\"><p helvetica=\"\" neue\",=\"\" helvetica,=\"\" arial,=\"\" sans-serif;=\"\" font-size:=\"\" 14px;=\"\" background-color:=\"\" #ffffff;=\"\" text-decoration-style:=\"\" initial;=\"\" text-decoration-color:=\"\" initial;\"=\"\" style=\"color: #333333;\">Über  Projektinfos, Workshops, Vorstellung unserer Werte und Visionen, sowie  über die praktische Mitarbeit in kleinen Arbeitsgruppen können die  TeilnehmerInnen unsere Gemeinschaft kennenlernen. Themen wie  Gemeinschaftsbildung, Transformation der Ökonomie, Kommunikationskultur,  Konsensentscheidungen werden vorgestellt und im Gruppenprozess erlebt</p></div><br />"
            }
        ],
        "teaserPictureUrl": [
            {
                "language": "DE",
                "value": "https://schloss-tempelhof.seminardesk.de/Content/Extern/DSC00235-300x200[1].jpg"
            }
        ],
        "priceInfo": [
            {
                "language": "DE",
                "value": "nach Selbsteinschätzung"
            }
        ],
        "facilitators": [
            111,
            112,
            113
        ],
        "venue": null,
        "contactInfo": null,
        "eventType": "Kennenlernwochenende",
        "eventTopic": "Schloss Tempelhof Kennenlernen",
        "showAttendanceFees": true
    }
}

### 792 - a15ec74c662b48458677dd7ad0b830f1 - Helfender Gast: Mitleben, mitwirken und mitwerkeln am Tempelhof

POST {{url}}
Authorization: {{auth}}
Content-Type: {{content}}

{
    "action": "eventDate.create",
    "timestamp": 1583509808000,
    "requestId": "3b27fe327ae240bf838a3fb6693e9feb",
    "payload": {
        "id": 792,
        "eventId": "a15ec74c662b48458677dd7ad0b830f1",
        "status": "available",
        "registrationAvailable": true,
        "detailpageAvailable": true,
        "beginDate": "1591545600000",
        "endDate": "1592132400000",
        "title": [
            {
                "language": "DE",
                "value": "Helfender Gast: Mitleben, mitwirken und mitwerkeln am Tempelhof"
            }
        ],
        "titleSlug": [
            {
                "language": "DE",
                "value": "helfender-gast-mitleben-mitwirken-und-mitwerkeln-am-tempelhof"
            }
        ],
        "subtitle": [
            {
                "language": "DE",
                "value": "Helfender Gast am Tempelhof"
            }
        ],
        "teaser": [
            {
                "language": "DE",
                "value": "Wir laden herzlich dazu ein, durch einen zeitweisen Aufenthalt als  helfender Gast am Tempelhof unser Gemeinschaftsleben zu erfahren. In den  verschiedenen Projekten, Arbeitsbereichen, beim Essen und weiteren  Aktionen begegnen sich die Menschen der Gemeinschaft und die  UnterstützerInnen und BesucherInnen – der Tempelhof wird so zur sozialen  Zukunftswerkstatt.<br />"
            }
        ],
        "teaserPictureUrl": [
            {
                "language": "DE",
                "value": "https://schloss-tempelhof.seminardesk.de/Content/Extern/Gasthelfer1.jpg"
            }
        ],
        "priceInfo": [],
        "facilitators": [],
        "venue": null,
        "contactInfo": null,
        "eventType": "Gasthelfer",
        "eventTopic": "Schloss Tempelhof Kennenlernen",
        "showAttendanceFees": false
    }
}

### 793 - a15ec74c662b48458677dd7ad0b830f1 - Helfender Gast: Mitleben, mitwirken und mitwerkeln am Tempelhof

POST {{url}}
Authorization: {{auth}}
Content-Type: {{content}}

{
    "action": "eventDate.create",
    "timestamp": 1583509808000,
    "requestId": "3b27fe327ae240bf838a3fb6693e9feb",
    "payload": {
        "id": 793,
        "eventId": "a15ec74c662b48458677dd7ad0b830f1",
        "status": "available",
        "registrationAvailable": true,
        "detailpageAvailable": true,
        "beginDate": "1592150400000",
        "endDate": "1592737200000",
        "title": [
            {
                "language": "DE",
                "value": "Helfender Gast: Mitleben, mitwirken und mitwerkeln am Tempelhof"
            }
        ],
        "titleSlug": [
            {
                "language": "DE",
                "value": "helfender-gast-mitleben-mitwirken-und-mitwerkeln-am-tempelhof"
            }
        ],
        "subtitle": [
            {
                "language": "DE",
                "value": "Helfender Gast am Tempelhof"
            }
        ],
        "teaser": [
            {
                "language": "DE",
                "value": "Wir laden herzlich dazu ein, durch einen zeitweisen Aufenthalt als  helfender Gast am Tempelhof unser Gemeinschaftsleben zu erfahren. In den  verschiedenen Projekten, Arbeitsbereichen, beim Essen und weiteren  Aktionen begegnen sich die Menschen der Gemeinschaft und die  UnterstützerInnen und BesucherInnen – der Tempelhof wird so zur sozialen  Zukunftswerkstatt.<br />"
            }
        ],
        "teaserPictureUrl": [
            {
                "language": "DE",
                "value": "https://schloss-tempelhof.seminardesk.de/Content/Extern/Gasthelfer1.jpg"
            }
        ],
        "priceInfo": [],
        "facilitators": [],
        "venue": null,
        "contactInfo": null,
        "eventType": "Gasthelfer",
        "eventTopic": "Schloss Tempelhof Kennenlernen",
        "showAttendanceFees": false
    }
}

### 794 - a15ec74c662b48458677dd7ad0b830f1 - Helfender Gast: Mitleben, mitwirken und mitwerkeln am Tempelhof

POST {{url}}
Authorization: {{auth}}
Content-Type: {{content}}

{
    "action": "eventDate.create",
    "timestamp": 1583509808000,
    "requestId": "3b27fe327ae240bf838a3fb6693e9feb",
    "payload": {
        "id": 794,
        "eventId": "a15ec74c662b48458677dd7ad0b830f1",
        "status": "available",
        "registrationAvailable": true,
        "detailpageAvailable": true,
        "beginDate": "1592755200000",
        "endDate": "1593342000000",
        "title": [
            {
                "language": "DE",
                "value": "Helfender Gast: Mitleben, mitwirken und mitwerkeln am Tempelhof"
            }
        ],
        "titleSlug": [
            {
                "language": "DE",
                "value": "helfender-gast-mitleben-mitwirken-und-mitwerkeln-am-tempelhof"
            }
        ],
        "subtitle": [
            {
                "language": "DE",
                "value": "Helfender Gast am Tempelhof"
            }
        ],
        "teaser": [
            {
                "language": "DE",
                "value": "Wir laden herzlich dazu ein, durch einen zeitweisen Aufenthalt als  helfender Gast am Tempelhof unser Gemeinschaftsleben zu erfahren. In den  verschiedenen Projekten, Arbeitsbereichen, beim Essen und weiteren  Aktionen begegnen sich die Menschen der Gemeinschaft und die  UnterstützerInnen und BesucherInnen – der Tempelhof wird so zur sozialen  Zukunftswerkstatt.<br />"
            }
        ],
        "teaserPictureUrl": [
            {
                "language": "DE",
                "value": "https://schloss-tempelhof.seminardesk.de/Content/Extern/Gasthelfer1.jpg"
            }
        ],
        "priceInfo": [],
        "facilitators": [],
        "venue": null,
        "contactInfo": null,
        "eventType": "Gasthelfer",
        "eventTopic": "Schloss Tempelhof Kennenlernen",
        "showAttendanceFees": false
    }
}

### 795 - a15ec74c662b48458677dd7ad0b830f1 - Helfender Gast: Mitleben, mitwirken und mitwerkeln am Tempelhof

POST {{url}}
Authorization: {{auth}}
Content-Type: {{content}}

{
    "action": "eventDate.create",
    "timestamp": 1583509808000,
    "requestId": "3b27fe327ae240bf838a3fb6693e9feb",
    "payload": {
        "id": 795,
        "eventId": "a15ec74c662b48458677dd7ad0b830f1",
        "status": "available",
        "registrationAvailable": true,
        "detailpageAvailable": true,
        "beginDate": "1593360000000",
        "endDate": "1593946800000",
        "title": [
            {
                "language": "DE",
                "value": "Helfender Gast: Mitleben, mitwirken und mitwerkeln am Tempelhof"
            }
        ],
        "titleSlug": [
            {
                "language": "DE",
                "value": "helfender-gast-mitleben-mitwirken-und-mitwerkeln-am-tempelhof"
            }
        ],
        "subtitle": [
            {
                "language": "DE",
                "value": "Helfender Gast am Tempelhof"
            }
        ],
        "teaser": [
            {
                "language": "DE",
                "value": "Wir laden herzlich dazu ein, durch einen zeitweisen Aufenthalt als  helfender Gast am Tempelhof unser Gemeinschaftsleben zu erfahren. In den  verschiedenen Projekten, Arbeitsbereichen, beim Essen und weiteren  Aktionen begegnen sich die Menschen der Gemeinschaft und die  UnterstützerInnen und BesucherInnen – der Tempelhof wird so zur sozialen  Zukunftswerkstatt.<br />"
            }
        ],
        "teaserPictureUrl": [
            {
                "language": "DE",
                "value": "https://schloss-tempelhof.seminardesk.de/Content/Extern/Gasthelfer1.jpg"
            }
        ],
        "priceInfo": [],
        "facilitators": [],
        "venue": null,
        "contactInfo": null,
        "eventType": "Gasthelfer",
        "eventTopic": "Schloss Tempelhof Kennenlernen",
        "showAttendanceFees": false
    }
}

### 796 - a15ec74c662b48458677dd7ad0b830f1 - Helfender Gast: Mitleben, mitwirken und mitwerkeln am Tempelhof

POST {{url}}
Authorization: {{auth}}
Content-Type: {{content}}

{
    "action": "eventDate.create",
    "timestamp": 1583509808000,
    "requestId": "3b27fe327ae240bf838a3fb6693e9feb",
    "payload": {
        "id": 796,
        "eventId": "a15ec74c662b48458677dd7ad0b830f1",
        "status": "available",
        "registrationAvailable": true,
        "detailpageAvailable": true,
        "beginDate": "1593964800000",
        "endDate": "1594551600000",
        "title": [
            {
                "language": "DE",
                "value": "Helfender Gast: Mitleben, mitwirken und mitwerkeln am Tempelhof"
            }
        ],
        "titleSlug": [
            {
                "language": "DE",
                "value": "helfender-gast-mitleben-mitwirken-und-mitwerkeln-am-tempelhof"
            }
        ],
        "subtitle": [
            {
                "language": "DE",
                "value": "Helfender Gast am Tempelhof"
            }
        ],
        "teaser": [
            {
                "language": "DE",
                "value": "Wir laden herzlich dazu ein, durch einen zeitweisen Aufenthalt als  helfender Gast am Tempelhof unser Gemeinschaftsleben zu erfahren. In den  verschiedenen Projekten, Arbeitsbereichen, beim Essen und weiteren  Aktionen begegnen sich die Menschen der Gemeinschaft und die  UnterstützerInnen und BesucherInnen – der Tempelhof wird so zur sozialen  Zukunftswerkstatt.<br />"
            }
        ],
        "teaserPictureUrl": [
            {
                "language": "DE",
                "value": "https://schloss-tempelhof.seminardesk.de/Content/Extern/Gasthelfer1.jpg"
            }
        ],
        "priceInfo": [],
        "facilitators": [],
        "venue": null,
        "contactInfo": null,
        "eventType": "Gasthelfer",
        "eventTopic": "Schloss Tempelhof Kennenlernen",
        "showAttendanceFees": false
    }
}

### 797 - a15ec74c662b48458677dd7ad0b830f1 - Helfender Gast: Mitleben, mitwirken und mitwerkeln am Tempelhof

POST {{url}}
Authorization: {{auth}}
Content-Type: {{content}}

{
    "action": "eventDate.create",
    "timestamp": 1583509808000,
    "requestId": "3b27fe327ae240bf838a3fb6693e9feb",
    "payload": {
        "id": 797,
        "eventId": "a15ec74c662b48458677dd7ad0b830f1",
        "status": "available",
        "registrationAvailable": true,
        "detailpageAvailable": true,
        "beginDate": "1594569600000",
        "endDate": "1595156400000",
        "title": [
            {
                "language": "DE",
                "value": "Helfender Gast: Mitleben, mitwirken und mitwerkeln am Tempelhof"
            }
        ],
        "titleSlug": [
            {
                "language": "DE",
                "value": "helfender-gast-mitleben-mitwirken-und-mitwerkeln-am-tempelhof"
            }
        ],
        "subtitle": [
            {
                "language": "DE",
                "value": "Helfender Gast am Tempelhof"
            }
        ],
        "teaser": [
            {
                "language": "DE",
                "value": "Wir laden herzlich dazu ein, durch einen zeitweisen Aufenthalt als  helfender Gast am Tempelhof unser Gemeinschaftsleben zu erfahren. In den  verschiedenen Projekten, Arbeitsbereichen, beim Essen und weiteren  Aktionen begegnen sich die Menschen der Gemeinschaft und die  UnterstützerInnen und BesucherInnen – der Tempelhof wird so zur sozialen  Zukunftswerkstatt.<br />"
            }
        ],
        "teaserPictureUrl": [
            {
                "language": "DE",
                "value": "https://schloss-tempelhof.seminardesk.de/Content/Extern/Gasthelfer1.jpg"
            }
        ],
        "priceInfo": [],
        "facilitators": [],
        "venue": null,
        "contactInfo": null,
        "eventType": "Gasthelfer",
        "eventTopic": "Schloss Tempelhof Kennenlernen",
        "showAttendanceFees": false
    }
}

### 798 - a15ec74c662b48458677dd7ad0b830f1 - Helfender Gast: Mitleben, mitwirken und mitwerkeln am Tempelhof

POST {{url}}
Authorization: {{auth}}
Content-Type: {{content}}

{
    "action": "eventDate.create",
    "timestamp": 1583509808000,
    "requestId": "3b27fe327ae240bf838a3fb6693e9feb",
    "payload": {
        "id": 798,
        "eventId": "a15ec74c662b48458677dd7ad0b830f1",
        "status": "available",
        "registrationAvailable": true,
        "detailpageAvailable": true,
        "beginDate": "1595174400000",
        "endDate": "1595761200000",
        "title": [
            {
                "language": "DE",
                "value": "Helfender Gast: Mitleben, mitwirken und mitwerkeln am Tempelhof"
            }
        ],
        "titleSlug": [
            {
                "language": "DE",
                "value": "helfender-gast-mitleben-mitwirken-und-mitwerkeln-am-tempelhof"
            }
        ],
        "subtitle": [
            {
                "language": "DE",
                "value": "Helfender Gast am Tempelhof"
            }
        ],
        "teaser": [
            {
                "language": "DE",
                "value": "Wir laden herzlich dazu ein, durch einen zeitweisen Aufenthalt als  helfender Gast am Tempelhof unser Gemeinschaftsleben zu erfahren. In den  verschiedenen Projekten, Arbeitsbereichen, beim Essen und weiteren  Aktionen begegnen sich die Menschen der Gemeinschaft und die  UnterstützerInnen und BesucherInnen – der Tempelhof wird so zur sozialen  Zukunftswerkstatt.<br />"
            }
        ],
        "teaserPictureUrl": [
            {
                "language": "DE",
                "value": "https://schloss-tempelhof.seminardesk.de/Content/Extern/Gasthelfer1.jpg"
            }
        ],
        "priceInfo": [],
        "facilitators": [],
        "venue": null,
        "contactInfo": null,
        "eventType": "Gasthelfer",
        "eventTopic": "Schloss Tempelhof Kennenlernen",
        "showAttendanceFees": false
    }
}

### 799 - a15ec74c662b48458677dd7ad0b830f1 - Helfender Gast: Mitleben, mitwirken und mitwerkeln am Tempelhof

POST {{url}}
Authorization: {{auth}}
Content-Type: {{content}}

{
    "action": "eventDate.create",
    "timestamp": 1583509808000,
    "requestId": "3b27fe327ae240bf838a3fb6693e9feb",
    "payload": {
        "id": 799,
        "eventId": "a15ec74c662b48458677dd7ad0b830f1",
        "status": "available",
        "registrationAvailable": true,
        "detailpageAvailable": true,
        "beginDate": "1595779200000",
        "endDate": "1596366000000",
        "title": [
            {
                "language": "DE",
                "value": "Helfender Gast: Mitleben, mitwirken und mitwerkeln am Tempelhof"
            }
        ],
        "titleSlug": [
            {
                "language": "DE",
                "value": "helfender-gast-mitleben-mitwirken-und-mitwerkeln-am-tempelhof"
            }
        ],
        "subtitle": [
            {
                "language": "DE",
                "value": "Helfender Gast am Tempelhof"
            }
        ],
        "teaser": [
            {
                "language": "DE",
                "value": "Wir laden herzlich dazu ein, durch einen zeitweisen Aufenthalt als  helfender Gast am Tempelhof unser Gemeinschaftsleben zu erfahren. In den  verschiedenen Projekten, Arbeitsbereichen, beim Essen und weiteren  Aktionen begegnen sich die Menschen der Gemeinschaft und die  UnterstützerInnen und BesucherInnen – der Tempelhof wird so zur sozialen  Zukunftswerkstatt.<br />"
            }
        ],
        "teaserPictureUrl": [
            {
                "language": "DE",
                "value": "https://schloss-tempelhof.seminardesk.de/Content/Extern/Gasthelfer1.jpg"
            }
        ],
        "priceInfo": [],
        "facilitators": [],
        "venue": null,
        "contactInfo": null,
        "eventType": "Gasthelfer",
        "eventTopic": "Schloss Tempelhof Kennenlernen",
        "showAttendanceFees": false
    }
}

### 800 - a15ec74c662b48458677dd7ad0b830f1 - Helfender Gast: Mitleben, mitwirken und mitwerkeln am Tempelhof

POST {{url}}
Authorization: {{auth}}
Content-Type: {{content}}

{
    "action": "eventDate.create",
    "timestamp": 1583509808000,
    "requestId": "3b27fe327ae240bf838a3fb6693e9feb",
    "payload": {
        "id": 800,
        "eventId": "a15ec74c662b48458677dd7ad0b830f1",
        "status": "available",
        "registrationAvailable": true,
        "detailpageAvailable": true,
        "beginDate": "1596384000000",
        "endDate": "1596970800000",
        "title": [
            {
                "language": "DE",
                "value": "Helfender Gast: Mitleben, mitwirken und mitwerkeln am Tempelhof"
            }
        ],
        "titleSlug": [
            {
                "language": "DE",
                "value": "helfender-gast-mitleben-mitwirken-und-mitwerkeln-am-tempelhof"
            }
        ],
        "subtitle": [
            {
                "language": "DE",
                "value": "Helfender Gast am Tempelhof"
            }
        ],
        "teaser": [
            {
                "language": "DE",
                "value": "Wir laden herzlich dazu ein, durch einen zeitweisen Aufenthalt als  helfender Gast am Tempelhof unser Gemeinschaftsleben zu erfahren. In den  verschiedenen Projekten, Arbeitsbereichen, beim Essen und weiteren  Aktionen begegnen sich die Menschen der Gemeinschaft und die  UnterstützerInnen und BesucherInnen – der Tempelhof wird so zur sozialen  Zukunftswerkstatt.<br />"
            }
        ],
        "teaserPictureUrl": [
            {
                "language": "DE",
                "value": "https://schloss-tempelhof.seminardesk.de/Content/Extern/Gasthelfer1.jpg"
            }
        ],
        "priceInfo": [],
        "facilitators": [],
        "venue": null,
        "contactInfo": null,
        "eventType": "Gasthelfer",
        "eventTopic": "Schloss Tempelhof Kennenlernen",
        "showAttendanceFees": false
    }
}

### 801 - a15ec74c662b48458677dd7ad0b830f1 - Helfender Gast: Mitleben, mitwirken und mitwerkeln am Tempelhof

POST {{url}}
Authorization: {{auth}}
Content-Type: {{content}}

{
    "action": "eventDate.create",
    "timestamp": 1583509808000,
    "requestId": "3b27fe327ae240bf838a3fb6693e9feb",
    "payload": {
        "id": 801,
        "eventId": "a15ec74c662b48458677dd7ad0b830f1",
        "status": "available",
        "registrationAvailable": true,
        "detailpageAvailable": true,
        "beginDate": "1596988800000",
        "endDate": "1597575600000",
        "title": [
            {
                "language": "DE",
                "value": "Helfender Gast: Mitleben, mitwirken und mitwerkeln am Tempelhof"
            }
        ],
        "titleSlug": [
            {
                "language": "DE",
                "value": "helfender-gast-mitleben-mitwirken-und-mitwerkeln-am-tempelhof"
            }
        ],
        "subtitle": [
            {
                "language": "DE",
                "value": "Helfender Gast am Tempelhof"
            }
        ],
        "teaser": [
            {
                "language": "DE",
                "value": "Wir laden herzlich dazu ein, durch einen zeitweisen Aufenthalt als  helfender Gast am Tempelhof unser Gemeinschaftsleben zu erfahren. In den  verschiedenen Projekten, Arbeitsbereichen, beim Essen und weiteren  Aktionen begegnen sich die Menschen der Gemeinschaft und die  UnterstützerInnen und BesucherInnen – der Tempelhof wird so zur sozialen  Zukunftswerkstatt.<br />"
            }
        ],
        "teaserPictureUrl": [
            {
                "language": "DE",
                "value": "https://schloss-tempelhof.seminardesk.de/Content/Extern/Gasthelfer1.jpg"
            }
        ],
        "priceInfo": [],
        "facilitators": [],
        "venue": null,
        "contactInfo": null,
        "eventType": "Gasthelfer",
        "eventTopic": "Schloss Tempelhof Kennenlernen",
        "showAttendanceFees": false
    }
}

### 802 - a15ec74c662b48458677dd7ad0b830f1 - Helfender Gast: Mitleben, mitwirken und mitwerkeln am Tempelhof

POST {{url}}
Authorization: {{auth}}
Content-Type: {{content}}

{
    "action": "eventDate.create",
    "timestamp": 1583509808000,
    "requestId": "3b27fe327ae240bf838a3fb6693e9feb",
    "payload": {
        "id": 802,
        "eventId": "a15ec74c662b48458677dd7ad0b830f1",
        "status": "available",
        "registrationAvailable": true,
        "detailpageAvailable": true,
        "beginDate": "1597593600000",
        "endDate": "1598180400000",
        "title": [
            {
                "language": "DE",
                "value": "Helfender Gast: Mitleben, mitwirken und mitwerkeln am Tempelhof"
            }
        ],
        "titleSlug": [
            {
                "language": "DE",
                "value": "helfender-gast-mitleben-mitwirken-und-mitwerkeln-am-tempelhof"
            }
        ],
        "subtitle": [
            {
                "language": "DE",
                "value": "Helfender Gast am Tempelhof"
            }
        ],
        "teaser": [
            {
                "language": "DE",
                "value": "Wir laden herzlich dazu ein, durch einen zeitweisen Aufenthalt als  helfender Gast am Tempelhof unser Gemeinschaftsleben zu erfahren. In den  verschiedenen Projekten, Arbeitsbereichen, beim Essen und weiteren  Aktionen begegnen sich die Menschen der Gemeinschaft und die  UnterstützerInnen und BesucherInnen – der Tempelhof wird so zur sozialen  Zukunftswerkstatt.<br />"
            }
        ],
        "teaserPictureUrl": [
            {
                "language": "DE",
                "value": "https://schloss-tempelhof.seminardesk.de/Content/Extern/Gasthelfer1.jpg"
            }
        ],
        "priceInfo": [],
        "facilitators": [],
        "venue": null,
        "contactInfo": null,
        "eventType": "Gasthelfer",
        "eventTopic": "Schloss Tempelhof Kennenlernen",
        "showAttendanceFees": false
    }
}

### 803 - a15ec74c662b48458677dd7ad0b830f1 - Helfender Gast: Mitleben, mitwirken und mitwerkeln am Tempelhof

POST {{url}}
Authorization: {{auth}}
Content-Type: {{content}}

{
    "action": "eventDate.create",
    "timestamp": 1583509808000,
    "requestId": "3b27fe327ae240bf838a3fb6693e9feb",
    "payload": {
        "id": 803,
        "eventId": "a15ec74c662b48458677dd7ad0b830f1",
        "status": "available",
        "registrationAvailable": true,
        "detailpageAvailable": true,
        "beginDate": "1598803200000",
        "endDate": "1599390000000",
        "title": [
            {
                "language": "DE",
                "value": "Helfender Gast: Mitleben, mitwirken und mitwerkeln am Tempelhof"
            }
        ],
        "titleSlug": [
            {
                "language": "DE",
                "value": "helfender-gast-mitleben-mitwirken-und-mitwerkeln-am-tempelhof"
            }
        ],
        "subtitle": [
            {
                "language": "DE",
                "value": "Helfender Gast am Tempelhof"
            }
        ],
        "teaser": [
            {
                "language": "DE",
                "value": "Wir laden herzlich dazu ein, durch einen zeitweisen Aufenthalt als  helfender Gast am Tempelhof unser Gemeinschaftsleben zu erfahren. In den  verschiedenen Projekten, Arbeitsbereichen, beim Essen und weiteren  Aktionen begegnen sich die Menschen der Gemeinschaft und die  UnterstützerInnen und BesucherInnen – der Tempelhof wird so zur sozialen  Zukunftswerkstatt.<br />"
            }
        ],
        "teaserPictureUrl": [
            {
                "language": "DE",
                "value": "https://schloss-tempelhof.seminardesk.de/Content/Extern/Gasthelfer1.jpg"
            }
        ],
        "priceInfo": [],
        "facilitators": [],
        "venue": null,
        "contactInfo": null,
        "eventType": "Gasthelfer",
        "eventTopic": "Schloss Tempelhof Kennenlernen",
        "showAttendanceFees": false
    }
}

### 804 - a15ec74c662b48458677dd7ad0b830f1 - Helfender Gast: Mitleben, mitwirken und mitwerkeln am Tempelhof

POST {{url}}
Authorization: {{auth}}
Content-Type: {{content}}

{
    "action": "eventDate.create",
    "timestamp": 1583509808000,
    "requestId": "3b27fe327ae240bf838a3fb6693e9feb",
    "payload": {
        "id": 804,
        "eventId": "a15ec74c662b48458677dd7ad0b830f1",
        "status": "available",
        "registrationAvailable": true,
        "detailpageAvailable": true,
        "beginDate": "1599408000000",
        "endDate": "1599994800000",
        "title": [
            {
                "language": "DE",
                "value": "Helfender Gast: Mitleben, mitwirken und mitwerkeln am Tempelhof"
            }
        ],
        "titleSlug": [
            {
                "language": "DE",
                "value": "helfender-gast-mitleben-mitwirken-und-mitwerkeln-am-tempelhof"
            }
        ],
        "subtitle": [
            {
                "language": "DE",
                "value": "Helfender Gast am Tempelhof"
            }
        ],
        "teaser": [
            {
                "language": "DE",
                "value": "Wir laden herzlich dazu ein, durch einen zeitweisen Aufenthalt als  helfender Gast am Tempelhof unser Gemeinschaftsleben zu erfahren. In den  verschiedenen Projekten, Arbeitsbereichen, beim Essen und weiteren  Aktionen begegnen sich die Menschen der Gemeinschaft und die  UnterstützerInnen und BesucherInnen – der Tempelhof wird so zur sozialen  Zukunftswerkstatt.<br />"
            }
        ],
        "teaserPictureUrl": [
            {
                "language": "DE",
                "value": "https://schloss-tempelhof.seminardesk.de/Content/Extern/Gasthelfer1.jpg"
            }
        ],
        "priceInfo": [],
        "facilitators": [],
        "venue": null,
        "contactInfo": null,
        "eventType": "Gasthelfer",
        "eventTopic": "Schloss Tempelhof Kennenlernen",
        "showAttendanceFees": false
    }
}

### 805 - a15ec74c662b48458677dd7ad0b830f1 - Helfender Gast: Mitleben, mitwirken und mitwerkeln am Tempelhof

POST {{url}}
Authorization: {{auth}}
Content-Type: {{content}}

{
    "action": "eventDate.create",
    "timestamp": 1583509808000,
    "requestId": "3b27fe327ae240bf838a3fb6693e9feb",
    "payload": {
        "id": 805,
        "eventId": "a15ec74c662b48458677dd7ad0b830f1",
        "status": "available",
        "registrationAvailable": true,
        "detailpageAvailable": true,
        "beginDate": "1600012800000",
        "endDate": "1600599600000",
        "title": [
            {
                "language": "DE",
                "value": "Helfender Gast: Mitleben, mitwirken und mitwerkeln am Tempelhof"
            }
        ],
        "titleSlug": [
            {
                "language": "DE",
                "value": "helfender-gast-mitleben-mitwirken-und-mitwerkeln-am-tempelhof"
            }
        ],
        "subtitle": [
            {
                "language": "DE",
                "value": "Helfender Gast am Tempelhof"
            }
        ],
        "teaser": [
            {
                "language": "DE",
                "value": "Wir laden herzlich dazu ein, durch einen zeitweisen Aufenthalt als  helfender Gast am Tempelhof unser Gemeinschaftsleben zu erfahren. In den  verschiedenen Projekten, Arbeitsbereichen, beim Essen und weiteren  Aktionen begegnen sich die Menschen der Gemeinschaft und die  UnterstützerInnen und BesucherInnen – der Tempelhof wird so zur sozialen  Zukunftswerkstatt.<br />"
            }
        ],
        "teaserPictureUrl": [
            {
                "language": "DE",
                "value": "https://schloss-tempelhof.seminardesk.de/Content/Extern/Gasthelfer1.jpg"
            }
        ],
        "priceInfo": [],
        "facilitators": [],
        "venue": null,
        "contactInfo": null,
        "eventType": "Gasthelfer",
        "eventTopic": "Schloss Tempelhof Kennenlernen",
        "showAttendanceFees": false
    }
}

### 805 - a15ec74c662b48458677dd7ad0b830f1 - Helfender Gast: Mitleben, mitwirken und mitwerkeln am Tempelhof

POST {{url}}
Authorization: {{auth}}
Content-Type: {{content}}

{
    "action": "eventDate.create",
    "timestamp": 1583509808000,
    "requestId": "3b27fe327ae240bf838a3fb6693e9feb",
    "payload": {
        "id": 805,
        "eventId": "a15ec74c662b48458677dd7ad0b830f1",
        "status": "available",
        "registrationAvailable": true,
        "detailpageAvailable": true,
        "beginDate": "1600012800000",
        "endDate": "1600599600000",
        "title": [
            {
                "language": "DE",
                "value": "Helfender Gast: Mitleben, mitwirken und mitwerkeln am Tempelhof"
            }
        ],
        "titleSlug": [
            {
                "language": "DE",
                "value": "helfender-gast-mitleben-mitwirken-und-mitwerkeln-am-tempelhof"
            }
        ],
        "subtitle": [
            {
                "language": "DE",
                "value": "Helfender Gast am Tempelhof"
            }
        ],
        "teaser": [
            {
                "language": "DE",
                "value": "Wir laden herzlich dazu ein, durch einen zeitweisen Aufenthalt als  helfender Gast am Tempelhof unser Gemeinschaftsleben zu erfahren. In den  verschiedenen Projekten, Arbeitsbereichen, beim Essen und weiteren  Aktionen begegnen sich die Menschen der Gemeinschaft und die  UnterstützerInnen und BesucherInnen – der Tempelhof wird so zur sozialen  Zukunftswerkstatt.<br />"
            }
        ],
        "teaserPictureUrl": [
            {
                "language": "DE",
                "value": "https://schloss-tempelhof.seminardesk.de/Content/Extern/Gasthelfer1.jpg"
            }
        ],
        "priceInfo": [],
        "facilitators": [],
        "venue": null,
        "contactInfo": null,
        "eventType": "Gasthelfer",
        "eventTopic": "Schloss Tempelhof Kennenlernen",
        "showAttendanceFees": false
    }
}