# REST Client tests on https://github.com/tronalddump-io/tronald-app
@baseUrl = http://localhost/wpsdp/wp-json/wp/v2
@basic_auth = Basic seminardesk:^T4qeM4v$N8nEdUUdFm2Tv4c


### GET sd_events from wordpress instance
GET {{baseUrl}}/users

### POST 
POST {{baseUrl}}/
Authorization: Basic seminardesk:^T4qeM4v$N8nEdUUdFm2Tv4c